### ISSUE TITLE
File is corrupted: www/abiertos/todos/202006/20200625_orig.zip

### ISSUE THREAD

**Issue by tonioluna** [mayrop/datos-covid19in-mx#71]
Not only the filename is different from previous days, the file is corrupted and cannot be decompressed. The file from official goverment source looks ok (https://www.gob.mx/salud/documentos/datos-abiertos-152127)

**Comment by tonioluna** [comment]
Files for the following days are correct.

**Comment by mayrop** [comment]
Fix here: https://github.com/mayrop/covid19mx/commit/2e18f39d5a2d9130f2eea8ebfc057fb94f007f11

Zip files are much heavier now... We'll see if this keeps happening.

**Comment by tonioluna** [comment]
> Fix here: [2e18f39](https://github.com/mayrop/covid19mx/commit/2e18f39d5a2d9130f2eea8ebfc057fb94f007f11)
> 
> Zip files are much heavier now... We'll see if this keeps happening.

I know! Thanks for looking into this!
